# Post para criar um novo curso
POST http://localhost:3333/courses HTTP/1.1
Content-Type: application/json

{
  "title": "Cursor AI",
  "description": "Cursor AI é um editor de código inteligente"
}

###
# Post para criar vários cursos
POST http://localhost:3333/courses HTTP/1.1
Content-Type: application/json

[
  { "title": "Crewai", "description": "Crewai é um framework de IA para desenvolvimento de aplicativos" },
  { "title": "Multi agente com Crewai", "description": "Criando Multi Agent Systems com CrewAI" },
  { "title": "MCPs", "description": "MCPs são interfaces de comunicação para IA" },
  { "title": "Deploy com Crewai", "description": "Deploy de aplicações com CrewAI" },
  { "title": "Criando agentes com Agno" },
  { "title": "Soft Skills" },
  { "title": "Apps Desktop com Electron" },
  { "title": "Acessibilidade com ReactJS" }

]

###
# Get para buscar todos os cursos com paginação (página 1, limite 5)
GET http://localhost:3333/courses?page=2&limit=5 HTTP/1.1

###
# Get para buscar todos os cursos
GET http://localhost:3333/courses HTTP/1.1

###
# Get para buscar um curso pelo id
GET http://localhost:3333/courses/1 HTTP/1.1